# Generated by Django 5.2.16 on 2026-07-12 08:23

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=core.models.short_id('nt'), max_length=40, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('subscription_expiry', 'subscription_expiry'), ('new_follower', 'new_follower'), ('new_release', 'new_release'), ('verification_result', 'verification_result'), ('monthly_finance', 'monthly_finance'), ('new_ticket', 'new_ticket'), ('verification_request', 'verification_request')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('read', models.BooleanField(default=False)),
                ('href', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(default=core.models.short_id('pl'), max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('cover_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='engagement.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.track')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('playlist', 'track')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='engagement.PlaylistTrack', to='catalog.track'),
        ),
        migrations.CreateModel(
            name='RecentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('track', 'track'), ('playlist', 'playlist')], max_length=8)),
                ('ref_id', models.CharField(max_length=40)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
                'unique_together': {('user', 'kind', 'ref_id')},
            },
        ),
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.CharField(default=core.models.short_id('st'), max_length=40, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to='catalog.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'at'], name='engagement__user_id_1dbe3e_idx')],
            },
        ),
    ]
