# Generated by Django 5.2.16 on 2026-07-12 08:23

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(default=core.models.short_id('al'), max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('cover_url', models.CharField(blank=True, default='', max_length=500)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('genre', models.CharField(blank=True, default='', max_length=80)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='accounts.artist')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(default=core.models.short_id('tr'), max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('audio', models.FileField(blank=True, null=True, upload_to='tracks/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'flac'])])),
                ('source_url', models.CharField(blank=True, default='', max_length=500)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('cover_url', models.CharField(blank=True, default='', max_length=500)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('lyrics', models.TextField(blank=True, default='')),
                ('genre', models.CharField(blank=True, default='', max_length=80)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('single', 'single'), ('album', 'album')], default='single', max_length=8)),
                ('listeners', models.PositiveIntegerField(default=0)),
                ('streams', models.PositiveIntegerField(default=0)),
                ('early_access', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='catalog.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='accounts.artist')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_on', to='accounts.artist')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
