# Generated by Django 5.2.16 on 2026-07-12 08:23

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('silver', 'silver'), ('gold', 'gold')], max_length=16, unique=True)),
                ('monthly_price', models.PositiveIntegerField()),
                ('currency', models.CharField(default='تومان', max_length=16)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=core.models.short_id('pay'), max_length=40, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('silver', 'silver'), ('gold', 'gold')], max_length=16)),
                ('months', models.PositiveSmallIntegerField(choices=[(1, '1'), (3, '3'), (6, '6'), (12, '12')])),
                ('amount', models.PositiveIntegerField()),
                ('gateway', models.CharField(default='mock', max_length=16)),
                ('authority', models.CharField(blank=True, default='', max_length=128)),
                ('ref_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
