# Generated by Django 5.2.16 on 2026-07-12 08:23

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistMonthlyAccount',
            fields=[
                ('id', models.CharField(default=core.models.short_id('ac'), max_length=40, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=7)),
                ('unique_listeners', models.PositiveIntegerField(default=0)),
                ('streams', models.PositiveIntegerField(default=0)),
                ('reward', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('settled', 'settled')], default='pending', max_length=16)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.artist')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('artist', 'month')},
            },
        ),
    ]
