// Centralised query-key factory. Stable keys = predictable cache invalidation.

export const qk = {
  tracks: ["tracks"] as const,
  track: (id: string) => ["tracks", id] as const,
  albums: ["albums"] as const,
  album: (id: string) => ["albums", id] as const,
  artists: ["artists"] as const,
  artist: (id: string) => ["artists", id] as const,
  artistAlbums: (id: string) => ["artists", id, "albums"] as const,
  artistTracks: (id: string) => ["artists", id, "tracks"] as const,
  browse: (q: unknown) => ["browse", q] as const,
  userByHandle: (h: string) => ["users", "handle", h] as const,
  user: (id: string) => ["users", id] as const,
  playlists: (ownerId: string) => ["playlists", ownerId] as const,
  playlist: (id: string) => ["playlists", "one", id] as const,
  notifications: (userId: string) => ["notifications", userId] as const,
  unread: (userId: string) => ["notifications", userId, "unread"] as const,
  tickets: ["tickets"] as const,
  ticket: (id: string) => ["tickets", id] as const,
  verifications: ["verifications"] as const,
  verification: (id: string) => ["verifications", id] as const,
  accounting: ["accounting"] as const,
  prices: ["prices"] as const,
  todayStreams: (userId: string) => ["streams", userId, "today"] as const,
  recents: (userId: string) => ["recents", userId] as const,
  distribution: ["stats", "distribution"] as const,
  revenue: ["stats", "revenue"] as const,
} as const
